# Generated by Django 5.1.1 on 2024-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_bio_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_connection'),
        ),
    ]
