# Generated by Django 5.1.1 on 2024-10-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_connection_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection',
            new_name='Connections',
        ),
    ]
